// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:authentest_100/firebase_options.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFACMRK1cDjwrETRd8_5S8ZG3Nz6JGLgY',
    appId: '1:815506556767:android:3f2852547ab059070298ea',
    messagingSenderId: '815506556767',
    projectId: 'fir-test-100-ffc7f',
    storageBucket: 'fir-test-100-ffc7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApj2iyjfMcxmcqTYhgnDRkMyJ_SB8Bq_c',
    appId: '1:815506556767:ios:3139dd640e6a6eea0298ea',
    messagingSenderId: '815506556767',
    projectId: 'fir-test-100-ffc7f',
    storageBucket: 'fir-test-100-ffc7f.appspot.com',
    iosClientId:
        '815506556767-04broupdsokj9lcp4mpo1qs9v27ebthv.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest100',
  );
}
